services:
  app:
    tty: true
    networks:
      - app_network
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"  # ← Prisma Studio のポートを追加
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    env_file:
    - ./.env

  db:
    image: postgres:15
    hostname: db
    env_file:
      - ./.env
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      # 任意のSQLファイルを実行できるようにバインドマウント
      - ./sql/tmp:/tmp
      # confファイルをコンテナにバインドマウント
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf

networks:
  app_network:
    driver: bridge
volumes:
  node_modules: